// AUTO-GENERATED by scripts/mirror-cdsco-forms.ts. Do not edit by hand.
// Re-run the script to refresh URLs (idempotent).
//
// Forms marked "missing_v1" weren't downloadable from cdsco.gov.in at mirror
// time. Feature 6a should fall back to a "see CDSCO portal" link in the
// Submission Guide for those.

export type CDSCOFormStatus = "uploaded" | "missing_v1";

export type CDSCOFormEntry = {
  description: string;
  url: string | null;
  source_url: string | null;
  bytes: number;
  status: CDSCOFormStatus;
  tried?: string[];
};

export const CDSCO_FORMS = {
  "MD-5": {
    description: "Manufacturing license, Class A/B (state authority)",
    url: null,
    source_url: null,
    bytes: 0,
    status: "missing_v1",
    tried: ["https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD5n.pdf","https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD5.pdf"],
  },
  "MD-7": {
    description: "Application for manufacturing license, Class C/D",
    url: "https://bvremrydhnlrmuqnfixk.supabase.co/storage/v1/object/public/cdsco_forms/MD-7.pdf",
    source_url: "https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD7n.pdf",
    bytes: 878412,
    status: "uploaded",
  },
  "MD-9": {
    description: "Manufacturing license, Class C/D (central authority)",
    url: null,
    source_url: null,
    bytes: 0,
    status: "missing_v1",
    tried: ["https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD9n.pdf","https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD9.pdf"],
  },
  "MD-12": {
    description: "Test license (clinical investigation)",
    url: "https://bvremrydhnlrmuqnfixk.supabase.co/storage/v1/object/public/cdsco_forms/MD-12.pdf",
    source_url: "https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/MDMD12Tooltip.pdf",
    bytes: 794961,
    status: "uploaded",
  },
  "MD-14": {
    description: "Import license",
    url: "https://bvremrydhnlrmuqnfixk.supabase.co/storage/v1/object/public/cdsco_forms/MD-14.pdf",
    source_url: "https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD14n.pdf",
    bytes: 852044,
    status: "uploaded",
  },
  "MD-20": {
    description: "Export No Objection Certificate (NOC)",
    url: null,
    source_url: null,
    bytes: 0,
    status: "missing_v1",
    tried: ["https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD20n.pdf","https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD20.pdf"],
  },
  "MD-22": {
    description: "Clinical Investigation approval",
    url: "https://bvremrydhnlrmuqnfixk.supabase.co/storage/v1/object/public/cdsco_forms/MD-22.pdf",
    source_url: "https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD22.pdf",
    bytes: 820100,
    status: "uploaded",
  },
  "MD-23": {
    description: "Clinical Performance Evaluation for IVDs",
    url: null,
    source_url: null,
    bytes: 0,
    status: "missing_v1",
    tried: ["https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD23.pdf","https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/medical-device/FormMD23n.pdf"],
  },
} as const satisfies Record<string, CDSCOFormEntry>;

export type CDSCOFormId = keyof typeof CDSCO_FORMS;
