import { z } from "zod";
import {
  CdscoClassEnum,
  ClassQualifierEnum,
  InferenceMarkerSchema,
  ReadinessBandEnum,
  RiskLevelEnum,
  RecommendedPathEnum,
} from "./readiness-card";

/**
 * Phase 1.6 — Tier 1 ₹499 "Regulatory Readiness Report" output schema.
 *
 * Customer-facing PDF deliverable for the Tier 1 SKU. Six sections
 * exactly, mapped 1:1 to the spec docs (product brief + build brief).
 *
 * Generated by `lib/engine/readiness-report-v1-generator.ts` from the
 * existing `readiness_card` + wizard answers + three static lookup
 * libraries (effort/cost, reviewer priorities, smart examples).
 *
 * User-visible string fields are softened at generator time via
 * `softenCertainty()` and again at render time (belt-and-braces).
 * Banned-phrase constraints live in that utility, not in Zod.
 *
 * Boundary: this is decision-support, not submission-ready content.
 * Anything that would belong in a DMF / QMS / RMF / ACP write-up
 * belongs in Tier 2 (Submission Workspace), not here.
 */

export const ConfidenceLevelEnum = z.enum(["high", "medium", "low"]);
export type ConfidenceLevel = z.infer<typeof ConfidenceLevelEnum>;

export const ComplexityLevelEnum = z.enum(["low", "moderate", "high"]);
export type ComplexityLevel = z.infer<typeof ComplexityLevelEnum>;

export const GapPriorityEnum = z.enum(["P1", "P2", "P3"]);
export type GapPriority = z.infer<typeof GapPriorityEnum>;

export const SmartExampleCategoryEnum = z.enum([
  "intended_use",
  "claim_wording",
  "risk_justification",
]);
export type SmartExampleCategory = z.infer<typeof SmartExampleCategoryEnum>;

const MetaSchema = z.object({
  company_name: z.string(),
  product_name: z.string(),
  scoped_feature: z.string().nullable(),
  generated_at: z.string(),
  source_assessment_id: z.string(),
  /** Phase 2c — carry the synthesizer's inference markers (e.g. for
   *  hardware-persona reports) into the report payload so the PDF /
   *  on-screen renderer can show the same "what we assumed" block as
   *  the card. Optional / empty for SaMD / clinical-investigation
   *  reports. */
  inference_markers: z.array(InferenceMarkerSchema).optional(),
});

/**
 * Section 1 — Regulatory Scorecard.
 * Almost entirely derived from the existing readiness_card; zero new
 * LLM calls. Visual hero of the report.
 */
const ScorecardSchema = z.object({
  classification_label: z.string(),
  classification_class: CdscoClassEnum,
  classification_qualifier: ClassQualifierEnum,
  confidence: ConfidenceLevelEnum,
  complexity: ComplexityLevelEnum,
  pathway_label: z.string(),
  clinical_investigation_likely: z.boolean(),
  timeline_display: z.string(),
  cost_range_inr_display: z.string(),
  readiness_score: z.number().int().min(0).max(10).nullable(),
  readiness_band: ReadinessBandEnum,
  risk_level: RiskLevelEnum,
  top_gap_titles: z.array(z.string()).max(3),
  recommended_next_action: z.string(),
  triggers: z.array(z.string()).min(1).max(8),
});

/**
 * Section 2 — Your Likely Regulatory Pathway.
 * `why_this_class_applies` is one softened Opus call (tone-shift from
 * v2's consultant prose to founder-voice). Everything else derives
 * from readiness_card + static lookup.
 */
const PathwaySchema = z.object({
  why_this_class_applies: z.string(),
  authority: z.string(),
  forms: z.array(z.string()).min(1),
  step_sequence: z
    .array(
      z.object({
        step: z.string(),
        what_happens: z.string(),
        duration: z.string(),
      })
    )
    .min(2)
    .max(8),
  test_licence_note: z.string().nullable(),
  acp_note: z.string().nullable(),
});

/**
 * Section 3 — Readiness Gap Analysis (the most important section).
 * `gap`, `suggested_next_step`, `dim` come from readiness_card.top_gaps.
 * `priority` derives from severity. `estimated_effort` comes from the
 * static lookup keyed on `dim`. `why_it_matters` is one batched Opus
 * call that processes all gaps in one shot.
 */
const GapRowSchema = z.object({
  priority: GapPriorityEnum,
  gap: z.string(),
  why_it_matters: z.string(),
  suggested_next_step: z.string(),
  estimated_effort: z.string(),
  dim: z.string(),
});

const GapAnalysisSchema = z.object({
  rows: z.array(GapRowSchema).min(1).max(8),
});

/**
 * Section 4 — Timeline + Cost Estimator.
 * Phased breakdown is templated per (class, recommended_path) and
 * parameterized by the timeline range from readiness_card. No LLM
 * call — fully deterministic.
 */
const TimelineCostSchema = z.object({
  total_range_display: z.string(),
  total_anchor: z.string(),
  phases: z
    .array(
      z.object({
        name: z.string(),
        duration: z.string(),
        what_happens: z.string(),
        cost_range_inr: z.string(),
      })
    )
    .min(3)
    .max(7),
  bottlenecks: z.array(z.string()).max(5),
});

/**
 * Section 5 — Reviewer Insights.
 * Priorities pulled from the static reviewer-priorities library
 * indexed by {class, ai_ml_flag, recommended_path, data_sensitivity}.
 * Per-priority description tailored by one Opus call to product
 * specifics.
 */
const ReviewerInsightSchema = z.object({
  priority: z.string(),
  what_reviewers_look_for: z.string(),
});

/**
 * Section 6 — Smart Examples.
 * Good-vs-bad snippet pairs from the static library, indexed by
 * {class, ai_ml_flag, recommended_path}. Per-pair "why this is safer"
 * annotation tailored by one Opus call.
 * NEVER full forms — snippets only, per the product boundary.
 */
const SmartExampleSchema = z.object({
  category: SmartExampleCategoryEnum,
  topic: z.string(),
  good_snippet: z.string(),
  bad_snippet: z.string(),
  why_this_is_safer: z.string(),
});

export const ReadinessReportSchema = z.object({
  meta: MetaSchema,
  scorecard: ScorecardSchema,
  pathway: PathwaySchema,
  gap_analysis: GapAnalysisSchema,
  timeline_cost: TimelineCostSchema,
  reviewer_insights: z.array(ReviewerInsightSchema).min(3).max(8),
  smart_examples: z.array(SmartExampleSchema).min(2).max(6),
});

export type ReadinessReport = z.infer<typeof ReadinessReportSchema>;
export type Scorecard = z.infer<typeof ScorecardSchema>;
export type Pathway = z.infer<typeof PathwaySchema>;
export type GapRow = z.infer<typeof GapRowSchema>;
export type GapAnalysis = z.infer<typeof GapAnalysisSchema>;
export type TimelineCost = z.infer<typeof TimelineCostSchema>;
export type ReviewerInsight = z.infer<typeof ReviewerInsightSchema>;
export type SmartExample = z.infer<typeof SmartExampleSchema>;
